<a href="https://colab.research.google.com/github/Sihjp/Widi-Ardhiansyah-DAA-S3/blob/main/DAA_Struktur_data_dalam_python_Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
aList = ["john", 33, "Toronto", True]

In [ ]:
print(aList)

['john', 33, 'Toronto', True]


In [ ]:
import datetime

x = datetime.datetime.now()

#y = x.hour, x.month, x.day, x.year

mahasiswa = ["Widi", "2022071073", "INF", "DAA", x.strftime("%x"), "Universitas Pembangunan Jaya"]

In [ ]:
print(mahasiswa)

['Widi', '2022071073', 'INF', 'DAA', '09/11/23', 'Universitas Pembangunan Jaya']


In [ ]:
print(mahasiswa[1:3])

['2022071073', 'INF']


In [ ]:
#List[index:rentang]
bin_colors=['Red','Green','Blue', 'Yellow']
bin_colors[0:4]

['Red', 'Green', 'Blue', 'Yellow']

In [ ]:
bin_colors=['Red','Green','Blue', 'Yellow']
for aColor in bin_colors:
  print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
for index in mahasiswa:
  print("UPJ " + index)

UPJ Widi
UPJ 2022071073
UPJ INF
UPJ DAA
UPJ 09/11/23
UPJ Universitas Pembangunan Jaya


In [ ]:
# Tuples
bin_colors=['Red','Green','Blue', 'Yellow']
print(bin_colors[1:2],bin_colors[3:4])
print(bin_colors[3:4])

['Green'] ['Yellow']
['Yellow']


In [ ]:
upj = ("Universitas", "Pembangunan", "Jaya")
upj

('Universitas', 'Pembangunan', 'Jaya')

In [ ]:
# Nested Tuple
hariAwal = ("Senin", "Selasa", "Rabu")
hariAkhir = ("Kamis", "Jumat", "Sabtu", "Minggu")
hari = (hariAwal, hariAkhir)
print(hari)

(('Senin', 'Selasa', 'Rabu'), ('Kamis', 'Jumat', 'Sabtu', 'Minggu'))


In [ ]:
# Latihan Tuple
Pertama = (100)
Kedua = (200, 400, 600)
Ketiga = (300)
keempat = (400, 800)
angka = (Pertama, Kedua, Ketiga, keempat)
print(angka)

(100, (200, 400, 600), 300, (400, 800))


In [ ]:
# Dictionary
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
bin_colors.get('approved_color')
bin_colors['approved_color']='Green'
# isi dari variabel bin_colors berubah menjadi = 'Green'

In [ ]:
bin_colors['approved_color']= "Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [ ]:
#latihan Dictionary
data_Mhs = {
    "Nama_Mhs": "Widi",
    "Nim_Mhs": "2022071073",
    "Prod_Mhs": "Informatika",
    "Univ_Mhs": "UPJ"
}

print(data_Mhs)

{'Nama_Mhs': 'Widi', 'Nim_Mhs': '2022071073', 'Prod_Mhs': 'Informatika', 'Univ_Mhs': 'UPJ'}


In [ ]:
#Inisiasi set dan mengubah list menjadi set
#inisiasi set
set_01 = {4,5,6,2}
print(set_01)

#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])
print(type(set_02))
print(set_03)

{2, 4, 5, 6}
<class 'set'>
{1, 2, 3, 4}


In [ ]:
set_03 = {4,5,6,2}
print(set_03[1])

TypeError: ignored

In [ ]:
# Menambah anggota set
set_04 = {2,3,4,5,6}
set_04.add(1)
print(set_04)

{1, 2, 3, 4, 5, 6}


In [ ]:
set_04 = {1,2,3,4,5,6,7,8}
set_04.discard(4) #menghapus nilai 4 dalam set
print(set_04)

{1, 2, 3, 5, 6, 7, 8}


In [ ]:
set_04.add(10) #menambahkan nilai 10 pada sets
print(set_04)

{1, 2, 3, 5, 6, 7, 8, 10}


In [ ]:
#Union set
# Union set adalah menggabungkan semua anggota set.
set_A = {1,2,3,4}
set_B = {3,4,5,6}
print(set_A|set_B)
print(set_A.union(set_B))

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}


In [ ]:
#intersection / irisan set
# mencari nilai irisan dari dua bua set (mencari bilangan/ nilai yang sama).

print(set_A&set_B)
print(set_A.intersection(set_B))

{3, 4}
{3, 4}


In [ ]:
#Difference Set
#Mencari perbedaan anggota atau nilai dari dua buah set atau lebih.
# A - B
print(set_A - set_B)
print(set_A.difference(set_B))


{1, 2}
{1, 2}


In [ ]:
# B - A
print(set_B - set_A)
print(set_B.difference(set_A))

{5, 6}
{5, 6}


In [ ]:
#Symmetric Difference adalah semua anggota pada set A dan set B dikurangi dengan anggota
#yang berada pada dua set tersebut.
# symmetric difference dapat dilakukan dengan menggunakan tanda (^) atau menggunakan metode symmetric_difference().

print(set_A ^ set_B)
print(set_A.symmetric_difference(set_B))

{1, 2, 5, 6}
{1, 2, 5, 6}


In [ ]:
# Latihan set
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'leaves', 'blood', 'rose','fire hydrant'}
print(yellow|red)
print(yellow&red)

{'leaves', 'dandelions', 'rose', 'fire hydrant', 'blood'}
{'leaves', 'fire hydrant'}


In [ ]:
# Data Frames

import pandas as pd
# sebelum nya df = pd.DataFrames ({ Data... }) dan terjadi error.
df = pd.DataFrame([
    ['1','Fares', 32 , True],
    ['2','Elea', 23 , False],
    ['3','Steven', 40 , True]
    ])
# sebelum nya df.colums dan kode masih tetap berjalan walaupun ada kesalahan penulisan kurang n.
df.columns = ['id','name','age','decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2    Elea   23     False
2  3  Steven   40      True

In [ ]:
# Data Frames

import pandas as pd
# sebelum nya df = pd.DataFrames ({ Data... }) dan terjadi error.
df = pd.DataFrame([
    ['1','Fares', 32 , True],
    ['2','Elea', 23 , False],
    ['3','Steven', 40 , True]
    ])
# sebelum nya df.colums dan kode masih tetap berjalan walaupun ada kesalahan penulisan kurang n.
df.columns = ['id','name','age','decision']
df

# Seleksi kolom
df[['name', 'age']]

decision
0      True
1     False
2      True

In [ ]:
# Data Frames

import pandas as pd
# sebelum nya df = pd.DataFrames ({ Data... }) dan terjadi error.
df = pd.DataFrame([
    ['1','Fares', 32 , True],
    ['2','Elea', 23 , False],
    ['3','Steven', 40 , True]
    ])
# sebelum nya df.colums dan kode masih tetap berjalan walaupun ada kesalahan penulisan kurang n.
df.columns = ['id','name','age','decision']
df

# Row selection
# Dari masing-masing perintah di bawah terdapat output nya sendiri.
df.iloc[1:3,:]

df[df.age>30]

df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [ ]:
# Memberikan index label seperti pada Series
data = {'satu': [1,1,1,1,1],
        'dua': [2,2,2,2,2],
        'tiga': [3,3,3,3,3]}
# perintah di bawah untuk menambahkan indeks.
df = pd.DataFrame(data, index=['a','b','c','d','e'])
# perintah ini untuk menampilkan hasil dari kode di atas.
df.head()

satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3

In [ ]:
# Latihan
data = {'No': [1,2,3],
    'Prodi': ['Informatika', 'Sistem Informasi', 'Teknik Sipil'],
    'Mahasiswa': [50,55,40],
    'Laki-Laki': [30,30,30],
    'Perempuan': [20,25,10]}

df = pd.DataFrame(data, index=[' ',' ',' '])
df.head()

No             Prodi  Mahasiswa  Laki-Laki  Perempuan
    1       Informatika         50         30         20
    2  Sistem Informasi         55         30         25
    3      Teknik Sipil         40         30         10

In [ ]:
# Matrix
import numpy as np
myMatrix = np.array([[11, 12, 13],[21, 22, 23],[31, 32, 33]])
print(myMatrix)
print(type(myMatrix))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [ ]:
# Transpose matrix
import numpy as np
matriksC = np.array([[1,2,3],[4,5,6]])
print('Matriks C : ')
print(matriksC)
print("\n")
transpose_matriks = np.transpose(matriksC)

print("Transpose Matriks C : ")
print(transpose_matriks)

Matriks C : 
[[1 2 3]
 [4 5 6]]


Transpose Matriks C : 
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Latihan
import numpy as np
bwaah = np.array([[100,200,300],[700,600,500],[900,1000,800]])
print("bwaah is for : ")
print(bwaah)
print("\n")

transpose_matriks = np.transpose(bwaah)
print("transpose nih bos : ")
print(transpose_matriks)

bwaah is for : 
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


transpose nih bos : 
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


#Tipe data abstrak


*   Abstraksi, secara umum, adalah konsep yang digunakan untuk mendefinisikan sistem yang kompleks dalam hal fungsi inti umum mereka.

*   Penggunaan konsep ini untuk membuat struktur data generik melahirkan Tipe Data Abstrak (ADT).

*   Dengan menyembunyikan detail tingkat implementasi dan memberi pengguna struktur data generik yang tidak bergantung pada implementasi, penggunaan ADT menciptakan algoritma yang menghasilkan kode yang lebih sederhana dan lebih bersih.

*   ADT dapat diimplementasikan dalam bahasa pemrograman apa pun seperti C++, Java, dan Scala.

In [ ]:
# Tipe data abstrak : vector
import numpy as np
# menggunakan list python
myVector = [22,33,44,55]
print (myVector)
print(type(myVector))

print("\n")

# menggunakan array numpy
myVector = np.array([22,33,44,55])
print(myVector)
print(type(myVector))

[22, 33, 44, 55]
<class 'list'>


[22 33 44 55]
<class 'numpy.ndarray'>


#Tipe data abstrak : stack

* Stack adalah struktur data linier untuk menyimpan daftar satu dimensi. Itu dapat menyimpan item baik dengan cara Last-In, First-Out (LIFO) atau First-In, Last-Out (FILO).

* Berikut ini adalah operasi yang berhubungan dengan stack:
isEmpty: Mengembalikan nilai true jika tumpukan kosong
push: Menambahkan elemen baru
pop: Mengembalikan elemen yang ditambahkan terakhir dan menghapusnya

In [11]:
# tipe data stack
import numpy as np

# Create the stack
stack = []

# Populate the stack
stack.append('Red')
stack.append('Green')
stack.append('Blue')
stack.append('Yellow')

# Perform stack pop
stack.pop()

# Check if stack is empty


'Yellow'

In [12]:
class Stack:
  def __init__(self) :
      self.items = []
  def isEmpty(self):
      return self.items == []
  def push(self, item):
      self.items.append(item)
  def pop(self):
      return self.items.pop()
  def peek(self):
      return self.items[len(self.items)-1]
  def size(self):
      return len(self.items)

#Queue

* Seperti stack, antrian menyimpan n elemen dalam struktur satu dimensi.
* Elemen ditambahkan dan dihapus dalam format FIFO.


In [19]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [22]:
queue = Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

print(queue.dequeue())

print(queue.dequeue())

4
Red
Green


#Tipe data abstrak:Tree

* Setiap tree memiliki kumpulan node yang terbatas sehingga memiliki elemen data awal yang disebut root dan kumpulan node yang disatukan oleh tautan yang disebut branch.

- Ada berbagai jenis tree:
  * Binary tree
  * Full tree
  * Perfect tree
  * Ordered tree

#Istilah yang penting pada tree
- Tree artinya pohon.Mengacu pada pohon pada dunia nyata yang di mana memiliki akar daun dan ranting
- Node paling atas (tidak punya predecessor) disebut Root
- Node yang berada di atas node tertentu = Predecessor
- Node yang berada di bawah node tertentu = Successor
- Predecessor satu level = Parent
- Sucessor satu level = Child
- Seluruh Node sebelum node tertentu dan berada pada jalur yang sama = Ancestor
- Seluruh Node setelah node tertentu dan berada pada jalur yang sama = Descendants
- Node-node yang memiliki parent yang sama = Sibling
- Bagian dari tree beserta descendants nya = Subtree
- Node yang tidak punya successor = Leaf
- Jumlah node dalam suatu tree = Size
- Jumlah tingkatan tree = Height
- Banyaknya child yang dimiliki suatu node = Degree


#Binary tree
Contoh paling simple penerapan tree adalah direktori dalam komputer di dalam direktori ada folder kemudian di dalam ada subfolder dst.

Dalam matematika untuk membuat faktorisasi prima dari suatu bilangan kita bisa memakai pohon faktor.
Seperti ini contoh pohon faktor

* Pohon Faktor

  - 120 adalah Root
  - 2,3,5 adalah Leaf karena mereka tidak bercabang
  - 60 dan 2,30 dan 2, 15 dan 2,3 dan 5  descendants dari 120
  - 30 dan 2,15 dan 2,3 dan 5 descendants dari 60
  - 15 dan 2,3 dan 5 descendants dari 30
  - 3 dan 5 descendats dari 15

In [26]:
# Binary tree pada Python
class node:
    def __init__(self, data):
        self.left = None
        self.right = None
        self.data = data

    def PrintTree(self):
        if self.left:
            self.left.PrintTree()
        print(self.data)
        if self.right:
            self.right.PrintTree()

root = node(2)  # root
root.left = node(3)  # child kiri dari root
root.right = node(5)  # child kanan dari root
root.left.left = node(7)  # child kiri dari 3
root.left.right = node(9)  # child kanan dari 3
root.right.left = node(11)  # child kiri dari 5
root.right.right = node(13)  # child kanan dari 5

root.PrintTree()

7
3
9
2
11
5
13
